/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Ecosystem;
import Business.Manufacturer.Manufacturer;
import Business.Manufacturer.ManufacturerDirectory;
import Business.Role.ManufacturerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pushk
 */
public class AddManufacturerJPanel extends javax.swing.JPanel {

    JPanel CardLayoutJPanel;
    Ecosystem business;
    Manufacturer manufacturer;
    UserAccount useraccount;
    /**
     * Creates new form AddRestuarantJPanel
     */
   public AddManufacturerJPanel(JPanel CardLayoutJPanel, Ecosystem business, UserAccount useraccount) {
        initComponents();
        this.CardLayoutJPanel =CardLayoutJPanel;
        this.business = business;
        this.useraccount=useraccount;
       
    }              

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtUsername = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JTextField();
        TxtContact = new javax.swing.JTextField();
        Savebtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Manufacturer Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 50));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Username:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Password:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Phone number:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });
        add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, -1));
        add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, -1));
        add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 170, -1));
        add(TxtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 170, -1));

        Savebtn.setBackground(new java.awt.Color(0, 0, 0));
        Savebtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(255, 255, 255));
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        add(Savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 80, -1));

        Backbtn.setBackground(new java.awt.Color(0, 0, 0));
        Backbtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("E-mail:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 60));
        add(Txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 170, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 32)); // NOI18N
        jLabel2.setText("Add Manufacturer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Picture/Ophthalmic-Medicine-Manufacturer-and-Supplier-1024x535.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 830, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        Manufacturer m=new Manufacturer();
        String manuName= TxtName.getText();
        String username = TxtUsername.getText();
        String password= TxtPassword.getText();
        String phoneNo= TxtContact.getText();
        String email=Txtemail.getText();
        m.setManuName(manuName);
        m.setUserName(username);
        m.setPassword(password);
        m.setPhoneNumber(phoneNo);
        m.setEmailAddress(email);
        
        
       if(manuName.isEmpty() || phoneNo.isEmpty() || email.isEmpty()|| username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all fields!");
        }
        else if(!phoneFormat(phoneNo))
        {
            JOptionPane.showMessageDialog(null, "Phone format incorrect!");
        }
        else if(!business.getPatientDirectory().isPhoneUnique(phoneNo)){
            JOptionPane.showMessageDialog(null, "Phone No already registered!");
        }
        else if(!business.getUserAccountDirectory().checkIfUsernameIsUnique(username)){
            JOptionPane.showMessageDialog(null, "Username already exists!");
        }
       else{
            Manufacturer manufacturer = business.getManufacturerDirectory().addNewManufacturer(m);
            UserAccount account = business.getUserAccountDirectory().createUserAccount(username, password, m.getManuId(), new ManufacturerRole(), manufacturer);
            JOptionPane.showMessageDialog(null, "New Manufacturer added");
        }
    
    }                                       
    
        public boolean phoneFormat(String phoneNo){
        String regex = "^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(phoneNo);
        if(matcher.matches()){
            return true;
        }
        return false;
            
    }//GEN-LAST:event_SavebtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        SystemAdminManufacturerNewJPanel addmanu = new SystemAdminManufacturerNewJPanel(CardLayoutJPanel, business,useraccount);
        CardLayoutJPanel.add("AddManufacturerJPanel", addmanu);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
    }//GEN-LAST:event_BackbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Savebtn;
    private javax.swing.JTextField TxtContact;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JTextField Txtemail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
